### ISSUE TITLE
Missing signature on checkout page

### ISSUE THREAD

**Issue by NevillePerkins** [mr-kg/PayFast#1]
According to the latest official documentation at https://developers.payfast.co.za/documentation/#checkout-page you have to send the MD5 hash signature with your payment request. I do not see it anywhere in the solution?

**Comment by mr-kg** [comment]
Hi Neville, thanks for pointing this out. This may very well be a new requirement, as I have not encountered an issue with this in the past. I have no current PF integrations, so can't really confirm. I'll create a PR if I get a gap - if not, please feel free to do so.

**Comment by mr-kg** [comment]
Resolved :) Thanks Neville
